Fifth task
YaroslavaMalaya/database pull request #4
Opened 2024-04-13 21:56 UTC by YaroslavaMalaya

2024-04-15 20:01 UTC, Ivashchyk requested changes
Minor comments

2024-04-15 20:01 UTC, Ivashchyk commented on pa5/views.sql
> +        DATE(a.date) = '2024-02-14'
```suggestion
        DATE(a.date) = <today>
```

2024-04-15 20:01 UTC, Ivashchyk commented on pa5/views.sql
> +    CONCAT( DATE_FORMAT(MIN(a.date), '%H:%i'), '-', DATE_FORMAT(MAX(DATE_ADD(a.date, INTERVAL s.duration MINUTE)), '%H:%i')) AS time_from_to,
What do MIN() and MAX() mean here?

2024-04-15 20:01 UTC, Ivashchyk commented on pa5/views.sql
> +        JOIN employee_service es ON e.id = es.employee_id
```suggestion
        INNER JOIN employee_service es ON e.id = es.employee_id
```

2024-04-15 20:01 UTC, Ivashchyk commented on pa5/views.sql
> +        JOIN services s ON es.service_id = s.id
```suggestion
        INNER JOIN services s ON es.service_id = s.id
```

2024-04-15 20:01 UTC, Ivashchyk commented on pa5/views.sql
> +        JOIN appointment a ON e.id = a.employee_id
```suggestion
        INNER JOIN appointment a ON e.id = a.employee_id
```

2024-04-16 15:42 UTC, YaroslavaMalaya commented on pa5/views.sql
> +    CONCAT( DATE_FORMAT(MIN(a.date), '%H:%i'), '-', DATE_FORMAT(MAX(DATE_ADD(a.date, INTERVAL s.duration MINUTE)), '%H:%i')) AS time_from_to,
The MIN determines the earliest start time of the appointment for each  employee on the selected day (which is specified in WHERE). And MAX is accordingly the latest appointment to this employee. Since in one day the employee may have several appointments at different times, it is necessary to find the first and the last appointment.

2024-04-17 10:56 UTC, merged